enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
patches-version = "dev"

# add 'enabled = false' for not patching 

[Instagram]
version = "latest"
arch = "arm64-v8a"
dpi = "480"
#apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
build-mode = "apk"
included-patches = "'Hide ads' 'Sanitize sharing links' 'Disable signature check''Open links externally'"
exclusive-patches = true

[Reddit]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "apk"

[Twitter]
enabled = false
version = "auto"
dpi = "120-640"
arch = "arm64-v8a"
build-mode = "apk"
#apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
included-patches = "'Hide view count'"
