enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
patches-version = "dev"
cli-version = "dev"
# add 'enabled = false' for not patching 

[Instagram]
version = "auto"
arch = "arm64-v8a"
dpi = "480"
#apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
build-mode = "apk"
riplib = true
included-patches = "'Hide ads' 'Sanitize sharing links' 'Disable signature check''Open links externally'"
exclusive-patches = true

[Instagram-apkm]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
included-patches = "'Hide ads' 'Sanitize sharing links' 'Disable signature check''Open links externally'"
exclusive-patches = true
enable-magisk-update = true
arch = "all"
dpi = "480"
riplib = true
build-mode = "both"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "apk"
riplib = true

[Twitter]
version = "auto"
dpi = "120-640"
arch = "arm64-v8a"
build-mode = "apk"
riplib = true
#apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
included-patches = "'Hide view count'"
