enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching 

[Instagram]
# apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
dpi = "480"
arch = "arm64-v8a"
build-mode = "both"
version = "latest"
included-patches = "'Hide ads' 'Sanitize sharing links' 'Disable signature check'"
exclusive-patches = true
